// HospitalesSys/frontend/src/components/login.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom'; 
import './css/registro.css';

const Login = () => {
  const [formData, setFormData] = useState({
    usuario: '',
    contrasena: ''
  });

  const [mensaje, setMensaje] = useState('');
  const navigate = useNavigate(); 

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    axios.post('http://localhost:7000/login', formData)
      .then((res) => {
        const usuario = res.data;
        setMensaje(`Bienvenido, ${usuario.usuario}`);

        localStorage.setItem('usuario', JSON.stringify(usuario));

        setTimeout(() => {
          navigate('/home'); // o window.location.href = "/home";
        }, 1000);
      })
      .catch((err) => {
        const msg = err.response?.data?.details || "Error al iniciar sesión";
        setMensaje(String(msg));
      });
  };

  return (
    <div className="registro-container">
      <h2>Iniciar Sesión</h2>

      <form onSubmit={handleSubmit}>
        <label>Usuario</label>
        <input
          type="text"
          name="usuario"
          value={formData.usuario}
          onChange={handleChange}
          required
        />

        <label>Contraseña</label>
        <input
          type="password"
          name="contrasena"
          value={formData.contrasena}
          onChange={handleChange}
          required
        />

        <button type="submit">Ingresar</button>
      </form>

      {mensaje && <p>{mensaje}</p>}

      <Link to="/registro">¿No tienes cuenta? Regístrate</Link>
    </div>
  );
};

export default Login;

// Seguros/frontend/src/routes/Login.svelte
<script>
  import { onMount } from "svelte";
  import { navigate } from "svelte-routing";

  let email = "";
  let password = "";
  let errorMessage = "";

  async function login() {
    errorMessage = ""; // Limpiar errores anteriores

    const response = await fetch("http://localhost:8000/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password })
    });

    const data = await response.json();

    if (response.ok) {
      localStorage.setItem("token", data.token);
      navigate("/"); // Redirigir al home
    } else {
      errorMessage = data.error || "Error en el inicio de sesión";
    }
  }
</script>

<div class="login-container">
  <h2>Iniciar Sesión</h2>
  {#if errorMessage}
    <p class="error">{errorMessage}</p>
  {/if}
  <form on:submit|preventDefault={login}>
    <label for="email">Email:</label>
    <input id="email" type="email" bind:value={email} required />

    <label for="password">Contraseña:</label>
    <input id="password" type="password" bind:value={password} required />

    <button type="submit">Ingresar</button>
  </form>
</div>

<style>
  .login-container {
    width: 300px;
    margin: auto;
    text-align: center;
  }
  .error {
    color: red;
  }
  input {
    display: block;
    width: 100%;
    margin-bottom: 10px;
  }
</style>
